import { Edge, Node } from "@xyflow/react";
import { MENU } from "../../../components/helper/menu";
export const styleSeccion =
  "bg-transparent text-[var(--t)] text-xl w-[20rem] block bg-clip-text text-transparent font-bold bg-gradient-to-r from-[var(--bg1)] to-[var(--bg2)]";
export const styleText =
  "bg-[var(--c)] rounded-[8px] font-bold cursor-default text-[var(--t)] shadow-[0_0_6px_#BD34FE] text-lg";
export const styleTextURL =
  "bg-[var(--c)] rounded-[8px] cursor-default text-[var(--t)] shadow-[0_0_32px_var(--bg2)] text-lg";
// Normas internacionales ................................................
export const unionNodoPrincipalEdge: Edge[] = [
  {
    id: "e1-1",
    source: "1",
    target: "10",
    sourceHandle: "1",
    targetHandle: "2",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-1.1",
    source: "10",
    target: "10.1",
    sourceHandle: "4",
    targetHandle: "3",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-1.2",
    source: "10",
    target: "10.2",
    sourceHandle: "1",
    targetHandle: "2",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-1.3",
    source: "10",
    target: "10.3",
    sourceHandle: "3",
    targetHandle: "4",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-2",
    source: "1",
    target: "20",
    sourceHandle: "3",
    targetHandle: "4",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-2.1",
    source: "20",
    target: "20.1",
    sourceHandle: "1",
    targetHandle: "4",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-2.2",
    source: "20",
    target: "20.2",
    sourceHandle: "3",
    targetHandle: "4",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-2.3",
    source: "20",
    target: "20.3",
    sourceHandle: "2",
    targetHandle: "4",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-3",
    source: "1",
    target: "30",
    sourceHandle: "2",
    targetHandle: "1",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-3.1",
    source: "30",
    target: "30.1",
    sourceHandle: "2",
    targetHandle: "1",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-3.2",
    source: "30",
    target: "30.2",
    sourceHandle: "3",
    targetHandle: "4",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-3.3",
    source: "30",
    target: "30.3",
    sourceHandle: "4",
    targetHandle: "3",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-4",
    source: "1",
    target: "40",
    sourceHandle: "4",
    targetHandle: "3",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-4.1",
    source: "40",
    target: "40.1",
    sourceHandle: "4",
    targetHandle: "3",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-4.2",
    source: "40",
    target: "40.2",
    sourceHandle: "1",
    targetHandle: "3",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
  {
    id: "e1-4.3",
    source: "40",
    target: "40.3",
    sourceHandle: "2",
    targetHandle: "3",
    animated: true,
    style: { stroke: "var(--bg2)" },
  },
];
export const nodeNodoPrincipalEdge: Node[] = [
  {
    id: "1",
    position: { x: 40, y: 450 },
    type: "Section",
    data: {
      nodo: 1,
      source: "",
      label: "Ingeniería de Software",
      labelTitle: "",
    },
    className: styleSeccion,
  },
  {
    id: "10",
    position: { x: 60, y: 220 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Regulaciones de Software de Calidad",
      url: "",
    },
    draggable: false,
    className: styleText,
  },
  {
    id: "10.1",
    position: { x: -360, y: 100 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Normas Internacionales (ISO/IEC)",
      url: MENU[0].lista[0].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "10.2",
    position: { x: 40, y: -50 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Estándares de Calidad (IEE/CMMI)",
      url: MENU[0].lista[1].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "10.3",
    position: { x: 450, y: 100 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Estándares de Calidad (IEE/CMMI)",
      url: MENU[0].lista[2].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "20",
    position: { x: 460, y: 480 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Control de Requerimientos y Validación",
      url: "",
    },
    draggable: false,
    className: styleText,
  },
  {
    id: "20.1",
    position: { x: 700, y: 300 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Técnicas de Validación",
      url: MENU[1].lista[0].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "20.2",
    position: { x: 960, y: 500 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Revisión de Requerimientos",
      url: MENU[1].lista[1].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "20.3",
    position: { x: 700, y: 640 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Trazabilidad de Requerimientos",
      url: MENU[1].lista[2].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "30",
    position: { x: -10, y: 660 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: MENU[2].nombre_next,
      url: "",
    },
    draggable: false,
    className: styleText,
  },
  {
    id: "30.1",
    position: { x: 10, y: 850 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: MENU[2].lista[0].nombre,
      url: MENU[2].lista[0].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "30.2",
    position: { x: 460, y: 800 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: MENU[2].lista[1].nombre,
      url: MENU[2].lista[1].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "30.3",
    position: { x: -300, y: 800 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: MENU[2].lista[2].nombre,
      url: MENU[2].lista[2].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "40",
    position: { x: -300, y: 420 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: "Factores clave para éxito",
      url: "",
    },
    draggable: false,
    className: styleText,
  },
  {
    id: "40.1",
    position: { x: -800, y: 400 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: MENU[3].lista[0].nombre,
      url: MENU[3].lista[0].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "40.2",
    position: { x: -640, y: 220 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: MENU[3].lista[1].nombre,
      url: MENU[3].lista[1].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
  {
    id: "40.3",
    position: { x: -640, y: 570 },
    type: "Section",
    data: {
      nodo: 1,
      source: "bottom",
      label: MENU[3].lista[2].nombre,
      url: MENU[3].lista[2].ruta,
    },
    draggable: false,
    className: styleTextURL,
  },
];
